# Generated by Django 4.1.1 on 2022-09-17 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200)),
                ('product_model', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(default=uuid.uuid1, max_length=500, unique=True)),
                ('description', models.TextField(max_length=50)),
                ('ram', models.TextField(max_length=50)),
                ('Screensize', models.TextField(max_length=200)),
                ('processor', models.TextField(max_length=100)),
                ('storage', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image1', models.ImageField(default='', upload_to='photo/storetem')),
                ('image2', models.ImageField(default='', upload_to='photo/storetem')),
                ('image3', models.ImageField(default='', upload_to='photo/storetem')),
                ('is_available', models.BooleanField(default=True)),
                ('offerflage', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
