# Generated by Django 4.1.1 on 2022-09-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_product_variation_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Product',
            new_name='Product_name',
        ),
    ]
