# Generated by Django 4.1.1 on 2022-09-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_product_variation_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Product_name',
            new_name='Product',
        ),
    ]
