# Generated by Django 4.1.1 on 2022-09-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_name_variation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('ram', 'ram'), ('processor', 'processor')], max_length=100),
        ),
    ]
