# Generated by Django 4.1.1 on 2022-10-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offerflage',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.IntegerField(default=0),
        ),
    ]
