# Generated by Django 4.1.1 on 2022-10-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_offerflage_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
