# Generated by Django 4.1.1 on 2022-09-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_coupon_coupon_uesed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupon_Uesed',
            new_name='CouponUesed',
        ),
    ]
