# Generated by Django 4.1.1 on 2022-10-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderproduct_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='reduction',
            field=models.IntegerField(null=True),
        ),
    ]
