# Generated by Django 4.1.1 on 2022-10-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderproduct_reduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='reduction',
        ),
        migrations.AddField(
            model_name='order',
            name='reduction',
            field=models.IntegerField(default=0),
        ),
    ]
